#ifndef MAPCONTROLLER_GLOBAL_H
#define MAPCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAPCONTROLLER_LIB
# define MAPCONTROLLER_EXPORT Q_DECL_EXPORT
#else
# define MAPCONTROLLER_EXPORT Q_DECL_IMPORT
#endif

#endif // MAPCONTROLLER_GLOBAL_H
