#ifndef MEASURETERRAINAREA_GLOBAL_H
#define MEASURETERRAINAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MEASURETERRAINAREA_LIB
# define MEASURETERRAINAREA_EXPORT Q_DECL_EXPORT
#else
# define MEASURETERRAINAREA_EXPORT Q_DECL_IMPORT
#endif

#endif // MEASURETERRAINAREA_GLOBAL_H
