#ifndef DRAWSURFACELINE_GLOBAL_H
#define DRAWSURFACELINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DRAWSURFACELINE_LIB
# define DRAWSURFACELINE_EXPORT Q_DECL_EXPORT
#else
# define DRAWSURFACELINE_EXPORT Q_DECL_IMPORT
#endif

#endif // DRAWSURFACELINE_GLOBAL_H
