#ifndef PLUGININTERFACE_GLOBAL_H
#define PLUGININTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGININTERFACE_LIB
# define PLUGININTERFACE_EXPORT Q_DECL_EXPORT
#else
# define PLUGININTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGININTERFACE_GLOBAL_H
