#ifndef PLUGINMANAGER_GLOBAL_H
#define PLUGINMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINMANAGER_LIB
# define PLUGINMANAGER_EXPORT Q_DECL_EXPORT
#else
# define PLUGINMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINMANAGER_GLOBAL_H
