#ifndef EARTHDATAINTERFACE_GLOBAL_H
#define EARTHDATAINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EARTHDATAINTERFACE_LIB
# define EARTHDATAINTERFACE_EXPORT Q_DECL_EXPORT
#else
# define EARTHDATAINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // EARTHDATAINTERFACE_GLOBAL_H
