#ifndef SETTINGSMANAGER_GLOBAL_H
#define SETTINGSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SETTINGSMANAGER_LIB
# define SETTINGSMANAGER_EXPORT Q_DECL_EXPORT
#else
# define SETTINGSMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGSMANAGER_GLOBAL_H
