#ifndef DRAWSURFACEPOLYGON_GLOBAL_H
#define DRAWSURFACEPOLYGON_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DRAWSURFACEPOLYGON_LIB
# define DRAWSURFACEPOLYGON_EXPORT Q_DECL_EXPORT
#else
# define DRAWSURFACEPOLYGON_EXPORT Q_DECL_IMPORT
#endif

#endif // DRAWSURFACEPOLYGON_GLOBAL_H
