#ifndef ATLASMAINWINDOW_GLOBAL_H
#define ATLASMAINWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ATLASMAINWINDOW_LIB
# define ATLASMAINWINDOW_EXPORT Q_DECL_EXPORT
#else
# define ATLASMAINWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // ATLASMAINWINDOW_GLOBAL_H
